### ISSUE TITLE
`IObservable' is an ambiguous reference between `System.IObservable<T>' and `UniRx.IObservable<T>'

### ISSUE THREAD

**Issue by CryptoMikan** [kyubuns/AnimeRx#1]
This error occurred when AnimeRx importerd.

```
`IObservable' is an ambiguous reference between `System.IObservable<T>' and `UniRx.IObservable<T>'
```

Environment:
Unity 2018.1.0f2
WebGL
Scripting Runtime Version: .NET 4.x Equivalent
Api Compatibility Level: .NET 4.x

**Comment by kyubuns** [comment]
Thanks report
What version of UniRx do you use?
Please try version up UniRx.
I think that UniRx.IObservable is not defined in NET_4_6.
https://github.com/neuecc/UniRx/blob/master/Assets/Plugins/UniRx/Scripts/System/IObservable.cs
