### ISSUE TITLE
Shake or Punch?

### ISSUE THREAD

**Issue by slimshader** [kyubuns/AnimeRx#6]
Hi, fantastic library, planing to replace the one we use currently with AnimeRx because of great UniRx integration. Question: is the support for "higher level" tweens like Punch or Shake planned?

**Comment by kyubuns** [comment]
Thank you.
There's no plan to support a "higher level" move.
Why, the shuffle every frame? In seconds? Does it end in the middle? Do you end up in a random position?
Everyone thinks that what they imagine is different.

Sure, there seem to be a lot of people who want to make it, so I've added a sample.
Check it out.
https://github.com/kyubuns/AnimeRx#create-your-self

**Comment by slimshader** [comment]
Thanks, I think I understand. Will take a deeper look.

**Comment by kyubuns** [comment]
:+1: good luck
